[package]
name = "aiv-ota-ip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.4"
hyper = { version = "0.14.24", features = ["full"] }
once_cell = "1.17.0"
tokio = { version = "1.25.0", features = ["full"] }
tower = "0.4.13"
